// ui2/src/app/app.component.ts
import {Component} from '@angular/core';
import {NotificationsService} from './notifications.service';
import {UserService} from './user.service';
import {HttpService} from './http.service';
import {Router} from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [NotificationsService, UserService, HttpService]
})
export class AppComponent {

  public menu = [
    {
      name: 'Sources',
      url: '/sources',
      icon: 'fa-database'
    },
    {
      name: 'Profiles',
      url: '/profiles',
      icon: 'fa-cogs'
    }
  ];


  constructor(public notificationsService: NotificationsService, public userService: UserService, private router: Router) {
  }

  public isVisible(item) {
    return this.userService.getUser();
  };

  public isActive(path) {
    return this.router.url.indexOf(path) === 0;
  };

}

<div class="notification-wrapper">
  <div *ngFor="let e of notificationsService.getNotifications()"
       class="modal-content notification notification-animation">
    <i class="close fa fa-lg fa-times-circle" (click)="notificationsService.removeNotification(e.id)"></i>
    <span><i class="type-icon fa fa-lg" [ngClass]="e.type"></i>{{e.message}}</span>
  </div>
</div>

<nav class="navbar navbar-default navbar-fixed-top">
  <div>
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><img src="../assets/sputnik-logo.png"></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li [class.active]="isActive(menuItem.url)" *ngFor="let menuItem of menu" [class.hidden]="!isVisible(menuItem)">
          <a [routerLink]="menuItem.url">
            <i class="fa fa-lg" [ngClass]="menuItem.icon"></i>
            <span class="li-text">{{menuItem.name}}</span>
          </a>
        </li>
        <li *ngIf="!userService.getUser()">
          <a routerLink="/signin">Sign in</a>
        </li>
        <li *ngIf="userService.getUser()">
          <a href="" title="Sign out" (click)="userService.signout()">
            <i class="fa fa-lg fa-power-off"></i>
            <span class="li-text">{{userService.getUser()}}</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<router-outlet></router-outlet>

// ui-react/src/App.jsx
import React from 'react';
import '../node_modules/font-awesome/css/font-awesome.css';
import './styles/bootstrap-spacelab.min.css';
import './styles/main.css';
import './styles/notification.css';
import logo from './assets/sputnik-logo.png'

import notificationService from './services/NotificationService';
import userService from './services/UserService';
import Notifications from './components/Notifications';
import Signin from './components/Signin';
import DataSources from './components/DataSources';

import {HashRouter as Router, Route, Link, NavLink} from 'react-router-dom'

const Home = () => (
    <div className="app-body">
        <h1>Home</h1>
    </div>
);


class App extends React.Component {

    componentDidMount() {
        userService.subscribe(() => this.forceUpdate());
    }

    render() {
        return (
            <div>
                <Notifications/>
                {this.menu()}
            </div>
        );
    }

    signout(e) {
        e.preventDefault();
        userService.signout();
    }

    menu() {
        const mainMenu = [
            {
                name: 'Sources',
                url: '/sources',
                icon: 'fa-database'
            },
            {
                name: 'Profiles',
                url: '/profiles',
                icon: 'fa-cogs'
            }
        ];

        return (
            <Router>
                <div>
                    <nav className="navbar navbar-default navbar-fixed-top">
                        <div>
                            <div className="navbar-header">
                                <a className="navbar-brand" href="#"><img src={logo}/></a>
                            </div>
                            <div id="navbar" className="navbar-collapse collapse">
                                <ul className="nav navbar-nav navbar-right">
                                    {mainMenu.map((it) => this.menuItem(it))}
                                    {this.menuUser()}
                                </ul>
                            </div>
                        </div>
                    </nav>
                    <Route exact path="/" component={Home}/>
                    <Route path="/sources" component={DataSources}/>
                    <Route path="/signin" component={Signin}/>
                </div>
            </Router>
        )
    }

    menuUser() {
        return userService.getUser() ?  (
            <li className="btn-link">
                <a title="Sign out" onClick={(e) => this.signout(e)}>
                    <i className="fa fa-lg fa-power-off"></i>
                    <span className="li-text">{userService.getUser()}</span>
                </a>
            </li>
        ) : (
            <li>
                <Link to="/signin">Sign in</Link>
            </li>
        );
    }

    menuItem(it) {
        return (
            <li key={it.url}>
                <NavLink to={it.url} activeClassName="active">
                    <i className={`fa fa-lg ${it.icon}`}></i>
                    <span className="li-text">{it.name}</span>
                </NavLink>
            </li>
        )
    }

}

export default App;
