// ui2/src/app/signin/signin.component.ts
import {Component, OnInit} from '@angular/core';
import {UserService} from '../user.service';

@Component({
  selector: 'app-signin',
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.css']
})
export class SigninComponent implements OnInit {

  public errorMessage;
  public username;
  public password;

  constructor(private userService: UserService) {
  }

  ngOnInit() {
  }

  public clickOk = function (form) {
    let that = this;
    // this.userService.signin(this.username, this.password, this.error.bind(this));
    this.userService.signin(this.username, this.password, (e) => this.error(e));
  };

  private error(response) {
    let data = response.json();
    if (data && data.message) {
      this.errorMessage = data.message;
    } else {
      this.errorMessage = 'Request failed!';
    }
  }

}

<form class="signin-form center" #form="ngForm">
  <div class="form-group">
    <input class="form-control" type="text" placeholder="Anonymous" [(ngModel)]="username" name="username">
  </div>
  <div class="form-group">
    <input class="form-control" type="password" placeholder="password" [(ngModel)]="password" required name="password">
  </div>
  <div class="form-group">
    <button class="btn btn-primary" (click)="clickOk(form)" [disabled]="!form.valid">Sign in</button>
  </div>
  <div class="label label-danger">{{errorMessage}}</div>
</form>

// ui-react/src/components/Signin.js
import React from 'react';
import userService from '../services/UserService';

class Signin extends React.Component {

    constructor() {
        super();
        this.state = {};
        this.handleInputChange = this.handleInputChange.bind(this);
    }

    handleInputChange(event) {
        const target = event.target;
        const value = target.type === 'checkbox' ? target.checked : target.value;
        const name = target.name;
        this.state[name] = value;
        this.forceUpdate();
    }

    render() {
        return (
            <form className="signin-form center" data-ng-controller="SigninController">
                <div className="form-group">
                    <input className="form-control" type="text" placeholder="Anonymous" name="username" value={this.state.username}
                           onChange={this.handleInputChange}/>
                </div>
                <div className="form-group">
                    <input className="form-control" type="password" placeholder="password" name="password" value={this.state.password}
                           onChange={this.handleInputChange} />
                </div>
                <div className="form-group">
                    <button className="btn btn-primary" onClick={(e) => this.clickOk(e)} disabled={!this.state.password}>
                        Sign in
                    </button>
                </div>
                <div className="label label-danger">{this.state.errorMessage}</div>
            </form>
        )
    };

    clickOk(e) {
        e.preventDefault();
        var that = this;
        userService.signin(this.state.username, this.state.password).then(
            response => {
            },
            error => {
                that.state.errorMessage = error.data.message;
                that.forceUpdate();
            });
    }

}

export default Signin;
